name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies and build Next.js
        run: |
          cd client
          npm install --force
          npm run build
      # Additional steps for deploying Next.js go here

  deploy-nestjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies and build Nest.js
        run: |
          cd server
          npm install
          # Any additional build steps
      - name: Start Nest.js server
        run: npm start
      # Additional steps for deploying Nest.js go here
