name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies and build Next.js
        run: |
          cd client
          npm install --force
          npm run build
      # Additional steps for deploying Next.js go here

  deploy-nestjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies and build Nest.js
        run: |
          cd server
          npm install
      - name: Install Nest.js CLI
        run: npm install --save-dev @nestjs/cli

      - name: Start Nest.js server
        run: npx nest start
